version: "3"

services:

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.8.2-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"

  concept-harvester:
    image: eu.gcr.io/digdir-fdk-infra/fdk-concept-harvester:latest
    environment:
      - RABBIT_USERNAME=admin
      - RABBIT_PASSWORD=admin
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
      - HARVEST_ADMIN_ROOT_URL=https://admin-api.staging.fellesdatakatalog.digdir.no/api
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
      - rabbitmq

  dataservice-harvester:
    image: eu.gcr.io/digdir-fdk-infra/fdk-dataservice-harvester:latest
    environment:
      - RABBIT_USERNAME=admin
      - RABBIT_PASSWORD=admin
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
      - HARVEST_ADMIN_ROOT_URL=https://admin-api.staging.fellesdatakatalog.digdir.no/api
    ports:
      - "8082:8080"
    depends_on:
      - mongodb
      - rabbitmq

  dataset-harvester:
    image: eu.gcr.io/digdir-fdk-infra/fdk-dataset-harvester:latest
    environment:
      - RABBIT_USERNAME=admin
      - RABBIT_PASSWORD=admin
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
      - HARVEST_ADMIN_ROOT_URL=https://admin-api.staging.fellesdatakatalog.digdir.no/api
    ports:
      - "8083:8080"
    depends_on:
      - mongodb
      - rabbitmq

  event-harvester:
    image: eu.gcr.io/digdir-fdk-infra/fdk-event-harvester:latest
    environment:
      - RABBIT_USERNAME=admin
      - RABBIT_PASSWORD=admin
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
      - HARVEST_ADMIN_ROOT_URL=https://admin-api.staging.fellesdatakatalog.digdir.no/api
    ports:
      - "8084:8080"
    depends_on:
      - mongodb
      - rabbitmq

  infomodel-harvester:
    image: eu.gcr.io/digdir-fdk-infra/fdk-informationmodel-harvester:latest
    environment:
      - RABBIT_USERNAME=admin
      - RABBIT_PASSWORD=admin
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
      - HARVEST_ADMIN_ROOT_URL=https://admin-api.staging.fellesdatakatalog.digdir.no/api
    ports:
      - "8085:8080"
    depends_on:
      - mongodb
      - rabbitmq

  public-service-harvester:
    image: eu.gcr.io/digdir-fdk-infra/fdk-public-service-harvester:latest
    environment:
      - RABBIT_USERNAME=admin
      - RABBIT_PASSWORD=admin
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
      - HARVEST_ADMIN_ROOT_URL=https://admin-api.staging.fellesdatakatalog.digdir.no/api
    ports:
      - "8086:8080"
    depends_on:
      - mongodb
      - rabbitmq
