logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
  level.org.apache.jena: ERROR
server:
  port: 8080
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
  data.mongodb.uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST:mongodb}:${MONGO_PORT:27017}/?authSource=admin&authMechanism=SCRAM-SHA-1
application:
  uri:
    organizations: ${ORGANIZATION_CATALOGUE_HOST}/organizations
    los: ${LOS_HOST:https://psi.norge.no/los/all.rdf}
  databases:
    datasets: datasetHarvester
    dataServices: dataServiceHarvester
    events: eventHarvester
    concepts: conceptHarvester
    publicServices: publicServiceHarvester
    infoModels: informationModelHarvester

---
spring:
  config.activate.on-profile: develop
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  data.mongodb.uri: mongodb://admin:admin@localhost:27017/?authSource=admin&authMechanism=SCRAM-SHA-1
application:
  uri:
    organizations: https://organization-catalogue.staging.fellesdatakatalog.digdir.no/organizations

---
spring:
  config.activate.on-profile: integration-test
application:
  uri:
    organizations: http://localhost:5000/organizations
    los: http://localhost:5000/los
