logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
  level.org.apache.jena: ERROR
server:
  port: 8080
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
  data.mongodb.uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST:mongodb}:${MONGO_PORT:27017}/?authSource=admin&authMechanism=SCRAM-SHA-1
application:
  uri:
    orgExternal: ${ORGANIZATION_CATALOG_EXTERNAL}/organizations
    orgInternal: ${ORGANIZATION_CATALOG_INTERNAL}/organizations
    los: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/los/themes-and-words
    eurovocs: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/eu/eurovocs
    dataThemes: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/eu/data-themes
    conceptStatuses: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/eu/concept-statuses
    conceptSubjects: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/digdir/concept-subjects
    ianaMediaTypes: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/iana/media-types
    fileTypes: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/eu/file-types
    openLicenses: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/open-licenses
    linguisticSystems: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/linguistic-systems
  databases:
    datasets: datasetHarvester
    dataServices: dataServiceHarvester
    events: eventHarvester
    concepts: conceptHarvester
    publicServices: publicServiceHarvester
    infoModels: informationModelHarvester

---
spring:
  config.activate.on-profile: develop
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  data.mongodb.uri: mongodb://admin:admin@localhost:27017/?authSource=admin&authMechanism=SCRAM-SHA-1
application:
  uri:
    orgExternal: https://organization-catalog.staging.fellesdatakatalog.digdir.no/organizations
    orgInternal: https://organization-catalog.staging.fellesdatakatalog.digdir.no/organizations

---
spring:
  config.activate.on-profile: integration-test
application:
  uri:
    orgExternal: http://localhost:5000/organizations
    orgInternal: http://localhost:5000/organizations
    los: http://localhost:5000/reference-data/los
    eurovocs: http://localhost:5000/reference-data/eu/eurovocs
    dataThemes: http://localhost:5000/reference-data/eu/data-themes
    conceptStatuses: http://localhost:5000/reference-data/eu/concept-statuses
    conceptSubjects: http://localhost:5000/reference-data/digdir/concept-subjects
    ianaMediaTypes: http://localhost:5000/reference-data/iana/media-types
    fileTypes: http://localhost:5000/reference-data/eu/file-types
