logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
  level.org.apache.jena: ERROR
server:
  port: 8080
application:
  uri:
    datasets: ${DATASETS_HOST:http://fdk-dataset-harvester:8080}/catalogs
    dataservices: ${DATASERVICES_HOST:http://fdk-dataservice-harvester:8080}/catalogs
    concepts: ${CONCEPTS_HOST:http://fdk-concept-harvester:8080}/collections
    informationmodels: ${INFOMODELS_HOST:http://fdk-informationmodel-harvester:8080}/catalogs
    events: ${EVENTS_HOST:http://fdk-event-harvester:8080}/events
    publicservices: ${PUBLIC_SERVICES_HOST:http://fdk-public-service-harvester:8080}/public-services
    organizations: ${ORGANIZATION_CATALOGUE_HOST}/organizations
    los: ${LOS_HOST:https://psi.norge.no/los/all.rdf}

---
spring:
  config.activate.on-profile: develop
application:
  uri:
    datasets: https://datasets.staging.fellesdatakatalog.digdir.no/catalogs
    dataservices: https://dataservices.staging.fellesdatakatalog.digdir.no/catalogs
    concepts: https://concepts.staging.fellesdatakatalog.digdir.no/collections
    informationmodels: https://informationmodels.staging.fellesdatakatalog.digdir.no/catalogs
    events: https://staging.fellesdatakatalog.digdir.no/api/events
    publicservices: https://staging.fellesdatakatalog.digdir.no/api/public-services
    organizations: https://organization-catalogue.staging.fellesdatakatalog.digdir.no/organizations

---
spring:
  config.activate.on-profile: integration-test
application:
  uri:
    datasets: http://localhost:5000/datasets/catalogs
    dataservices: http://localhost:5000/dataservices/catalogs
    concepts: http://localhost:5000/collections
    informationmodels: http://localhost:5000/informationmodels/catalogs
    events: http://localhost:5000/events
    publicservices: http://localhost:5000/public-services
    organizations: http://localhost:5000/organizations
