logging:
  level.root: WARN
  level.no.fdk: ${LOG_LEVEL:INFO}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
  level.org.apache.jena: ERROR
  level.org.apache.avro: ERROR
  level.org.apache.kafka: ERROR
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        info: ping
        health: ready
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: fdk-reasoning-service
server:
  port: 8080
application:
  uri:
    orgExternal: ${ORGANIZATION_CATALOG_EXTERNAL}/organizations
    orgInternal: ${ORGANIZATION_CATALOG_INTERNAL}/organizations
    los: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/los/themes-and-words
    eurovocs: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/eu/eurovocs
    dataThemes: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/eu/data-themes
    conceptStatuses: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/eu/concept-statuses
    conceptSubjects: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/digdir/concept-subjects
    ianaMediaTypes: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/iana/media-types
    fileTypes: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/eu/file-types
    openLicenses: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/open-licenses
    linguisticSystems: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/linguistic-systems
    geonorgeNasjoner: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/geonorge/administrative-enheter/nasjoner
    geonorgeFylker: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/geonorge/administrative-enheter/fylker
    geonorgeKommuner: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/geonorge/administrative-enheter/kommuner
    accessRights: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/eu/access-rights
    frequencies: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/eu/frequencies
    provenance: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/provenance-statements
    publisherTypes: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/adms/publisher-types
    admsStatuses: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/adms/statuses
    roleTypes: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/digdir/role-types
    evidenceTypes: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/digdir/evidence-types
    channelTypes: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/digdir/service-channel-types
    mainActivities: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/eu/main-activities
    weekDays: ${REFERENCE_DATA_HOST:https://staging.fellesdatakatalog.digdir.no}/reference-data/schema/week-days
  databases:
    datasets: datasetHarvester
    dataServices: dataServiceHarvester
    events: eventHarvester
    concepts: conceptHarvester
    publicServices: publicServiceHarvester
    infoModels: informationModelHarvester
spring:
  kafka:
    bootstrap-servers:
      - ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY:http://localhost:8081}
      specific.avro.reader: true
      auto.register.schemas: false
      use.latest.version: true
      value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
      key.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      compression-type: snappy
    listener:
      ack-mode: manual_immediate
resilience4j:
  circuitbreaker:
    instances:
      reasoning:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 60000
        automaticTransitionFromOpenToHalfOpenEnabled: true
---
spring:
  config.activate.on-profile: develop
application:
  uri:
    orgExternal: https://organization-catalog.staging.fellesdatakatalog.digdir.no/organizations
    orgInternal: https://organization-catalog.staging.fellesdatakatalog.digdir.no/organizations

---
spring:
  config.activate.on-profile: integration-test
application:
  uri:
    orgExternal: http://localhost:5050/organizations
    orgInternal: http://localhost:5050/organizations
    los: http://localhost:5050/reference-data/los
    eurovocs: http://localhost:5050/reference-data/eu/eurovocs
    dataThemes: http://localhost:5050/reference-data/eu/data-themes
    conceptStatuses: http://localhost:5050/reference-data/eu/concept-statuses
    conceptSubjects: http://localhost:5050/reference-data/digdir/concept-subjects
    ianaMediaTypes: http://localhost:5050/reference-data/iana/media-types
    fileTypes: http://localhost:5050/reference-data/eu/file-types
    openLicenses: http://localhost:5050/reference-data/open-licenses
    linguisticSystems: http://localhost:5050/reference-data/linguistic-systems
    geonorgeNasjoner: http://localhost:5050/reference-data/geonorge/administrative-enheter/nasjoner
    geonorgeFylker: http://localhost:5050/reference-data/geonorge/administrative-enheter/fylker
    geonorgeKommuner: http://localhost:5050/reference-data/geonorge/administrative-enheter/kommuner
    accessRights: http://localhost:5050/reference-data/eu/access-rights
    frequencies: http://localhost:5050/reference-data/eu/frequencies
    provenance: http://localhost:5050/reference-data/provenance-statements
    publisherTypes: http://localhost:5050/reference-data/adms/publisher-types
    admsStatuses: http://localhost:5050/reference-data/adms/statuses
    roleTypes: http://localhost:5050/reference-data/digdir/role-types
    evidenceTypes: http://localhost:5050/reference-data/digdir/evidence-types
    channelTypes: http://localhost:5050/reference-data/digdir/service-channel-types
    mainActivities: http://localhost:5050/reference-data/eu/main-activities
    weekDays: http://localhost:5050/reference-data/schema/week-days
