logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
  level.org.apache.jena: ERROR
server:
  port: 8080
application:
  uri:
    datasets: ${DATASETS_HOST:http://fdk-dataset-harvester:8080}/catalogs
    dataservices: ${DATASERVICES_HOST:http://fdk-dataservice-harvester:8080}/catalogs
    concepts: ${CONCEPTS_HOST:http://fdk-concept-harvester:8080}/collections
    organizations: ${ORGANIZATION_CATALOGUE_HOST}/organizations

---
spring:
  config.activate.on-profile: develop
application:
  uri:
    datasets: https://datasets.staging.fellesdatakatalog.digdir.no/catalogs
    dataservices: https://dataservices.staging.fellesdatakatalog.digdir.no/catalogs
    concepts: https://concepts.staging.fellesdatakatalog.digdir.no/collections
    organizations: https://organization-catalogue.staging.fellesdatakatalog.digdir.no/organizations

---
spring:
  config.activate.on-profile: integration-test
application:
  uri:
    datasets: http://localhost:5000/datasets/catalogs
    dataservices: http://localhost:5000/dataservices/catalogs
    concepts: http://localhost:5000/collections
    organizations: http://localhost:5000/organizations
