---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdk-reasoning-service
  labels:
    app: fdk-reasoning-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fdk-reasoning-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fdk-reasoning-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/prometheus"
    spec:
      containers:
        - name: fdk-reasoning-service
          image: fdk-reasoning-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          resources:
            requests:
              memory: 4500Mi
              cpu: 200m
            limits:
              memory: 4500Mi
