---
apiVersion: v1
kind: Service
metadata:
  name: fdk-kafka-reasoning-service
spec:
  selector:
    app: fdk-kafka-reasoning-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
